import test from 'node:test';import assert from 'node:assert/strict';import {validateAll} from '../scripts/validate.mjs';import {validateClan} from '../lore/validation.js';import {publicTechnique} from '../lore/technique.js';import {village,isOpen} from '../lore/common.js';
const clans=validateAll(),ids=clans.map(c=>c.id);
test('V1 always Konoha; V2 reads each original destination',()=>{for(const c of clans){assert.equal(village(c,{SERVER_PHASE:'V1'}),'Konoha');assert.equal(village(c,{SERVER_PHASE:'V2'}),c.v2Village);}assert.equal(village(clans.find(c=>c.id==='yuki'),{SERVER_PHASE:'V2'}),'Kiri');});
test('Public technique projection honors all four visibility levels',()=>{const base={...clans[0].techniques[0],description:'SECRET_DESCRIPTION_TEST'};assert.equal(publicTechnique({...base,visibility:'public'}).description,'SECRET_DESCRIPTION_TEST');const nameOnly=publicTechnique({...base,visibility:'name-only'});assert.equal(nameOnly.name,base.name);assert.equal(nameOnly.description,'');const classified=publicTechnique({...base,visibility:'classified'});assert.equal(classified.name,'Technique classifiée');assert.equal(classified.description,'');assert.equal(classified.requirements,'');assert.equal(publicTechnique({...base,visibility:'hidden'}),null);assert.equal(publicTechnique({...base,adminOnly:true}),null);assert.equal(publicTechnique({...base,enabled:false}),null);});
test('Hierarchy rejects cycles, missing parents, duplicates and invalid levels',()=>{for(const mutate of [c=>c.hierarchy[0].parent=c.hierarchy[1].id,c=>c.hierarchy[1].parent='missing',c=>c.hierarchy[1].id=c.hierarchy[0].id,c=>c.hierarchy[1].level=0]){const c=structuredClone(clans[0]);mutate(c);assert.throws(()=>validateClan(c,ids));}});
test('Schema rejects unsafe asset paths and unknown relations',()=>{const c=structuredClone(clans[0]);c.emblem='../../private';assert.throws(()=>validateClan(c,ids));c.emblem=clans[0].emblem;c.relations[0].targetClan='unknown';assert.throws(()=>validateClan(c,ids));});
test('Open filter uses actual enabled flag and free capacity',()=>{assert.equal(isOpen({enabled:true,maxMembers:4,members:['a']}),true);assert.equal(isOpen({enabled:true,maxMembers:1,members:['a']}),false);assert.equal(isOpen({enabled:false,maxMembers:4,members:[]}),false);assert.equal(isOpen({enabled:true,maxMembers:0,members:[]}),false);});
test('Original people, no duplicated membership and published secret contents omitted',()=>{const known=/^(Madara|Sasuke|Itachi|Obito|Shisui|Hinata|Neji|Hanabi|Hashirama|Tobirama|Tsunade|Naruto|Kushina|Karin|Minato|Gaara|Temari|Kankuro|Mei|Yagura|Haku|Kimimaro|Shikamaru|Shikaku|Chōji|Chōza|Rock|Might|Kagami)\b/;for(const c of clans){assert.ok(c.characters.every(p=>p.original&&!known.test(p.name)));assert.ok(!('members'in c));for(const t of c.techniques.filter(t=>t.secret&&t.visibility!=='public'))assert.equal(t.description,'');}});

