const visibleAt = (item, year, zoom) => (item.from ?? 0) <= year && (item.to ?? 9999) >= year && zoom >= (item.minZoom ?? 0);
export class MapLayers {
  constructor(canvas, world, camera) { this.canvas = canvas; this.world = world; this.camera = camera; this.year = 400; this.selected = null; this.pulse = 0; this.locationDetail = null; }
  setYear(year) { this.year = Number(year); }
  setEvent(event) { this.selected = event; }
  setLocationDetail(detail) { this.locationDetail = detail; }
  path(ctx, points) { ctx.beginPath(); points.forEach(([x,y], i) => { const p = this.camera.worldToScreen(x,y); i ? ctx.lineTo(p.x,p.y) : ctx.moveTo(p.x,p.y); }); }
  draw() {
    const ratio = this.camera.ratio || 1; const ctx = this.canvas.getContext("2d"); const w = this.canvas.width / ratio; const h = this.canvas.height / ratio;
    ctx.setTransform(ratio,0,0,ratio,0,0); const sea = ctx.createRadialGradient(w*.55,h*.46,20,w*.5,h*.5,Math.max(w,h)); sea.addColorStop(0,"#37545b"); sea.addColorStop(1,"#162932"); ctx.fillStyle=sea; ctx.fillRect(0,0,w,h);
    ctx.strokeStyle="rgba(210,226,220,.055)"; ctx.lineWidth=1; const grid=100; for(let x=0;x<=this.world.worldWidth;x+=grid){const a=this.camera.worldToScreen(x,0),b=this.camera.worldToScreen(x,this.world.worldHeight);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()} for(let y=0;y<=this.world.worldHeight;y+=grid){const a=this.camera.worldToScreen(0,y),b=this.camera.worldToScreen(this.world.worldWidth,y);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke()}
    this.world.lands.forEach(land=>{this.path(ctx,land.points);ctx.closePath();ctx.fillStyle=land.color;ctx.shadowColor="rgba(0,0,0,.38)";ctx.shadowBlur=16;ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle="rgba(236,224,190,.2)";ctx.lineWidth=1.4;ctx.stroke()});
    const state=this.world.states.find(s=>this.year>=s.from&&this.year<=s.to)||this.world.states.at(-1);
    this.world.countries.filter(i=>visibleAt(i,this.year,this.camera.zoom)).forEach(country=>{this.path(ctx,country.points);ctx.closePath();ctx.globalAlpha=.84;ctx.fillStyle=country.color;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle=state.accent;ctx.lineWidth=this.year===400?2:1.2;ctx.setLineDash([6,5]);ctx.stroke();ctx.setLineDash([]);if(this.camera.zoom<3){const cx=country.points.reduce((s,p)=>s+p[0],0)/country.points.length,cy=country.points.reduce((s,p)=>s+p[1],0)/country.points.length,p=this.camera.worldToScreen(cx,cy);ctx.fillStyle="rgba(255,247,222,.96)";ctx.shadowColor="rgba(0,0,0,.8)";ctx.shadowBlur=4;ctx.font=`600 ${Math.max(11,Math.min(17,11*this.camera.zoom))}px Georgia`;ctx.textAlign="center";ctx.fillText(country.name,p.x,p.y);ctx.shadowBlur=0}});
    this.world.rivers.filter(i=>visibleAt(i,this.year,this.camera.zoom)).forEach(river=>{this.path(ctx,river.points);ctx.strokeStyle="#7fb0b8";ctx.lineWidth=Math.max(1.5,2.2*this.camera.zoom/3);ctx.stroke()});
    this.world.routes.filter(i=>visibleAt(i,this.year,this.camera.zoom)&&state.activeRoutes.includes(i.id)).forEach(route=>{this.path(ctx,route.points);ctx.strokeStyle="rgba(238,202,130,.66)";ctx.lineWidth=2;ctx.setLineDash([7,6]);ctx.stroke();ctx.setLineDash([])});
    const locations=this.world.locations.filter(i=>visibleAt(i,this.year,this.camera.zoom)); locations.forEach(location=>this.drawLocation(ctx,location));
    if(this.locationDetail&&this.camera.zoom>=5){this.locationDetail.districts.forEach(d=>{const center=this.world.locations.find(l=>l.id===this.locationDetail.id),p=this.camera.worldToScreen(center.x+d.x/5,center.y+d.y/5);ctx.beginPath();ctx.arc(p.x,p.y,Math.max(8,d.radius*this.camera.baseScale*this.camera.zoom/7),0,Math.PI*2);ctx.fillStyle=d.color+"88";ctx.fill();ctx.strokeStyle="rgba(245,226,183,.45)";ctx.stroke();ctx.fillStyle="#f2ead7";ctx.font="12px system-ui";ctx.textAlign="center";ctx.fillText(d.name,p.x,p.y+4)})}
    if(this.selected) this.drawEvent(ctx,this.selected);
    this.pulse=(this.pulse+.03)%(Math.PI*2);
  }
  drawLocation(ctx,location){const p=this.camera.worldToScreen(location.x,location.y);const major=location.type.includes("village");ctx.beginPath();ctx.arc(p.x,p.y,major?5.5:3.5,0,Math.PI*2);ctx.fillStyle=major?"#f0d18c":"#d9cbb0";ctx.fill();ctx.strokeStyle="#182126";ctx.lineWidth=2;ctx.stroke();if(this.camera.zoom>=2.4||major){ctx.fillStyle="#f2ead7";ctx.font=`600 ${this.camera.zoom>5?14:12}px system-ui`;ctx.textAlign="center";ctx.fillText(location.name,p.x,p.y-10)}}
  drawEvent(ctx,event){const points=event.locations||[];if(points.length>1){this.path(ctx,points.map(p=>[p.x,p.y]));ctx.strokeStyle="rgba(231,111,101,.85)";ctx.lineWidth=2.5;ctx.setLineDash([9,6]);ctx.stroke();ctx.setLineDash([])}points.forEach((location,index)=>{const p=this.camera.worldToScreen(location.x,location.y),radius=9+Math.sin(this.pulse+index)*2;ctx.beginPath();ctx.arc(p.x,p.y,radius,0,Math.PI*2);ctx.strokeStyle="#ff766d";ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.arc(p.x,p.y,3.5,0,Math.PI*2);ctx.fillStyle="#fff2d2";ctx.fill()})}
  hitTest(worldPoint){return this.world.locations.filter(i=>visibleAt(i,this.year,this.camera.zoom)).map(location=>({location,d:Math.hypot(location.x-worldPoint.x,location.y-worldPoint.y)})).sort((a,b)=>a.d-b.d)[0]?.d < 18/this.camera.zoom ? this.world.locations.filter(i=>visibleAt(i,this.year,this.camera.zoom)).map(location=>({location,d:Math.hypot(location.x-worldPoint.x,location.y-worldPoint.y)})).sort((a,b)=>a.d-b.d)[0].location : null;}
}
