import {el,loadArchive,navigation,footer,clanURL,showError} from './common.js';import {validateClan} from './validation.js';import {renderHierarchy} from './hierarchy.js';
const shell=document.querySelector('#shell'),main=document.querySelector('main');shell.insertBefore(navigation('Administration'),main);shell.append(footer());
const editor=document.querySelector('#editor'),status=document.querySelector('#admin-status'),select=document.querySelector('#clan-select');let saved='',current='',ranks=[],clans=[];
const githubLink=el('a','filter-button','Modifier ce fichier sur GitHub ↗');githubLink.target='_blank';githubLink.rel='noopener noreferrer';document.querySelector('.action-row').append(githubLink);
function report(message){status.textContent=message;}
function parse(){const c=JSON.parse(editor.value);validateClan(c,clans.map(c=>c.id));if(c.id!==current)throw new Error('Conservez l’identifiant du dossier sélectionné.');return c;}
function drawRanks(){const box=document.querySelector('#rank-editor');box.replaceChildren();for(const [i,r] of ranks.entries()){const row=el('fieldset','record rank-form');row.append(el('legend','',`Grade ${i+1}`));for(const [key,label,type] of [['id','Identifiant','text'],['title','Nom du grade','text'],['description','Description','text'],['level','Niveau dans l’organigramme','number'],['accessLevel','Niveau d’accès RP','number']]){const field=el('label','form-row',label),input=el('input');input.type=type;input.value=r[key];if(type==='number')input.min='0';input.oninput=()=>{if(key==='id'){const old=r.id;ranks.forEach(child=>{if(child.parent===old)child.parent=input.value;});}r[key]=type==='number'?Number(input.value):input.value;};field.append(input);row.append(field);}const parentLabel=el('label','form-row','Identifiant du parent (vide = racine)'),parent=el('input');parent.value=r.parent||'';parent.oninput=()=>r.parent=parent.value||null;parentLabel.append(parent);row.append(parentLabel);const actions=el('div','action-row');for(const [label,delta] of [['Monter',-1],['Descendre',1]]){const b=el('button','filter-button',label);b.type='button';b.disabled=i+delta<0||i+delta>=ranks.length;b.onclick=()=>{[ranks[i],ranks[i+delta]]=[ranks[i+delta],ranks[i]];drawRanks();};actions.append(b);}const remove=el('button','filter-button','Supprimer ce grade');remove.type='button';remove.onclick=()=>{if(ranks.some(x=>x.parent===r.id)){report('Réaffectez les enfants de ce grade avant de le supprimer.');return;}ranks.splice(i,1);drawRanks();};actions.append(remove);row.append(actions);box.append(row);}}
function showClan(c){current=c.id;editor.value=JSON.stringify(c,null,2);saved=editor.value;ranks=structuredClone(c.hierarchy);drawRanks();document.querySelector('#hierarchy-preview').replaceChildren(renderHierarchy(c.hierarchy));document.querySelector('#source-path').textContent=`Fichier : data/lore/${c.id}.json`;document.querySelector('#public-link').href=clanURL(c.id);githubLink.href=`https://github.com/LuckyHamb/recensement-shinobi-renaissance/edit/feature/clan-lore/data/lore/${c.id}.json`;report('Dossier chargé.');}
try{({clans}=await loadArchive());for(const c of clans){const o=el('option','',c.name);o.value=c.id;select.append(o);}const requested=new URLSearchParams(location.search).get('id');select.value=clans.some(c=>c.id===requested)?requested:clans[0].id;showClan(clans.find(c=>c.id===select.value));select.onchange=()=>{if(editor.value!==saved&&!confirm('Changer de dossier et abandonner les modifications non téléchargées ?')){select.value=current;return;}showClan(clans.find(c=>c.id===select.value));};document.querySelector('#add-rank').onclick=()=>{let n=ranks.length+1;while(ranks.some(r=>r.id===`grade-${n}`))n++;ranks.push({id:`grade-${n}`,title:'Nouveau grade',description:'Responsabilité du grade',level:0,parent:null,accessLevel:0});drawRanks();};document.querySelector('#apply-ranks').onclick=()=>{try{const c=JSON.parse(editor.value);c.hierarchy=structuredClone(ranks);validateClan(c,clans.map(c=>c.id));editor.value=JSON.stringify(c,null,2);document.querySelector('#hierarchy-preview').replaceChildren(renderHierarchy(c.hierarchy));report('Organigramme valide, appliqué au dossier.');}catch(e){report(`Modification refusée : ${e.message}`);}};document.querySelector('#validate').onclick=()=>{try{const c=parse();ranks=structuredClone(c.hierarchy);drawRanks();document.querySelector('#hierarchy-preview').replaceChildren(renderHierarchy(c.hierarchy));report('Dossier valide. Organigramme actualisé.');}catch(e){report(`Dossier invalide : ${e.message}`);}};document.querySelector('#download').onclick=()=>{try{const c=parse();const objectURL=URL.createObjectURL(new Blob([JSON.stringify(c,null,2)+'\n'],{type:'application/json'}));const a=el('a');a.href=objectURL;a.download=`${c.id}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(objectURL),1000);saved=editor.value;report(`Fichier ${c.id}.json téléchargé. Intégrez-le dans data/lore/ sur votre branche GitHub.`);}catch(e){report(`Téléchargement refusé : ${e.message}`);}};}catch(e){showError(e);}
addEventListener('beforeunload',e=>{if(editor.value!==saved){e.preventDefault();e.returnValue='';}});

