import {el,link,paragraph,emblem,loadArchive,village,url,clanURL,showError,navigation,footer} from './common.js';
import {renderHierarchy} from './hierarchy.js';import {renderTimeline} from './timeline.js';import {renderTechnique} from './technique.js';
const main=document.querySelector('#clan-main');const shell=document.querySelector('#shell');shell.insertBefore(navigation(),main);shell.append(footer());
const sections=[['presentation','Présentation'],['histoire','Histoire'],['apparence','Apparence & mentalité'],['mode-de-vie','Mode de vie'],['hierarchie','Hiérarchie'],['traditions','Traditions'],['pouvoirs','Pouvoirs'],['techniques','Techniques'],['secrets','Secrets'],['personnalites','Personnalités'],['relations','Relations']];
try{const {clans,records,config}=await loadArchive();const id=new URLSearchParams(location.search).get('id');const c=clans.find(x=>x.id===id);if(!c)throw new Error('Identifiant de clan inconnu.');document.title=`${c.name} — Archives de Shinobi Renaissance`;document.querySelector('meta[name="description"]').content=`${c.tagline}. Histoire, traditions, pouvoirs et relations du clan ${c.name}.`;
 const crumb=el('nav','breadcrumb');crumb.setAttribute('aria-label','Fil d’Ariane');crumb.append(link('Archives des clans',url('lore/')),document.createTextNode(` / ${c.name}`));main.append(crumb);
 const hero=el('section','clan-hero');const copy=el('div');copy.append(el('p','eyebrow','Archives du clan'),el('h1','',c.displayName),el('p','masthead__title',c.tagline));const meta=el('div','clan-meta');const r=records.find(x=>x.id===c.id);for(const value of [village(c,config),...c.elements,c.specialties[0],c.status==='active'?'Actif':'Disparu',`${config.SERVER_PHASE} · Origine : ${c.originVillage}`])meta.append(el('span','',value));copy.append(meta,el('p','clan-quote',`« ${c.quote} »`));hero.append(emblem(c),copy);main.append(hero);const count=el('p','breadcrumb');count.append(link(`Membres recensés : ${r.members.length} / ${r.maxMembers} →`,url(`?clan=${encodeURIComponent(c.id)}#clans`)));main.append(count);
 const layout=el('div','reading-layout'),nav=el('nav','archive-nav'),content=el('div');nav.setAttribute('aria-label','Sommaire du dossier');for(const [key,label]of sections)nav.append(link(label,`#${key}`));layout.append(nav,content);main.append(layout);
 const sectionNodes=[];
 function imageFor(key){const items=c.illustrations.filter(i=>i.section===key);return items.map(i=>{const figure=el('figure',`illustration${i.layout==='portrait'?' illustration--portrait':''}`);const img=el('img');img.src=url(i.image);img.alt=i.alt;img.width=i.width;img.height=i.height;img.loading='lazy';img.decoding='async';figure.append(img,el('figcaption','',i.caption));return figure;});}
 for(const [key,label]of sections){const section=el('section','archive-section prose');section.id=key;section.setAttribute('aria-labelledby',`${key}-title`);section.append(el('p','section-kicker',`Dossier ${String(clans.indexOf(c)+1).padStart(2,'0')} · ${c.name}`));const h2=el('h2','',label);h2.id=`${key}-title`;section.append(h2);const illustrations=imageFor(key);illustrations.filter(i=>i.classList.contains('illustration--portrait')).forEach(i=>section.append(i));
 if(['presentation','apparence','mode-de-vie'].includes(key)){const field={presentation:'presentation',apparence:'appearance','mode-de-vie':'lifestyle'}[key];c[field].forEach(t=>section.append(paragraph(t)));}
 if(key==='histoire')section.append(renderTimeline(c.timeline,config.SERVER_PHASE));
 if(key==='hierarchie')section.append(renderHierarchy(c.hierarchy));
 if(key==='traditions')c.traditions.forEach(t=>section.append(el('h3','',t.title),paragraph(t.text)));
 if(key==='pouvoirs')c.powers.forEach(t=>section.append(el('h3','',t.title),paragraph(t.text)));
 if(['techniques','secrets'].includes(key)){const grid=el('div','record-grid');c.techniques.filter(t=>t.secret===(key==='secrets')).forEach(t=>{const card=renderTechnique(t);if(card)grid.append(card);});if(grid.childElementCount)section.append(grid);else section.append(paragraph('Aucun enseignement n’est ouvert à la consultation publique dans cette section.'));}
 if(key==='personnalites'){const grid=el('div','record-grid');c.characters.forEach(p=>{const card=el('article','record');card.append(el('p','section-kicker',p.role),el('h3','',p.name),paragraph(p.biography));grid.append(card);});section.append(grid);}
 if(key==='relations'){const grid=el('div','record-grid');c.relations.forEach(r=>{const other=clans.find(x=>x.id===r.targetClan);const card=el('article','record');const state=el('span','relation-status',r.status);state.dataset.relation=r.status;const h3=el('h3');h3.append(link(other.name,clanURL(other.id)));card.append(state,h3,paragraph(r.description),el('p','technique-meta',r.historicalReason));grid.append(card);});section.append(grid);}
 illustrations.filter(i=>!i.classList.contains('illustration--portrait')).forEach(i=>section.append(i));content.append(section);sectionNodes.push(section);}
 content.append(link(`⚙ Administrer le dossier ${c.name}`,url(`lore/administration/?id=${encodeURIComponent(c.id)}`),'archive-link'));
 let scheduled=false;function updateReading(){scheduled=false;let active=sectionNodes[0];for(const s of sectionNodes)if(s.getBoundingClientRect().top<160)active=s;nav.querySelectorAll('a').forEach(a=>{if(a.hash===`#${active.id}`)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});const range=document.documentElement.scrollHeight-innerHeight;document.documentElement.style.setProperty('--reading',`${range>0?Math.min(100,scrollY/range*100):100}%`);}
 addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(updateReading);}}, {passive:true});updateReading();if(location.hash){const target=document.getElementById(location.hash.slice(1));target?.scrollIntoView();}
}catch(error){showError(error);}finally{document.querySelector('#loading').hidden=true;main.setAttribute('aria-busy','false');}

