import {el,link,emblem,loadArchive,village,isOpen,normalize,clanURL,showError} from './common.js';
const state={query:'',filter:'Tous'};
const filters=['Tous','Konoha','Dōjutsu','Kekkei Genkai','Taijutsu','Ninjutsu','Clan ouvert','Clan disparu','Sans clan'];
const grid=document.querySelector('#clans');
document.querySelector('#retry').onclick=()=>location.reload();
try {
 const data=await loadArchive();
 const {clans,records,config}=data;
 document.querySelector('#phase').textContent=`${config.SERVER_PHASE} · ${new Set(clans.map(c=>village(c,config))).size===1?'Tous les chemins mènent à Konoha':'Les lignées retrouvent leurs terres'}`;
 const stats=[['Clans archivés',clans.length],['Villages',`${new Set(clans.map(c=>village(c,config))).size} — ${config.SERVER_PHASE}`],['Techniques secrètes',clans.reduce((n,c)=>n+(c.techniques||[]).filter(t=>t.secret&&t.enabled&&t.visibility!=='hidden'&&!t.adminOnly).length,0)],['Chroniques',clans.reduce((n,c)=>n+(c.timeline||[]).filter(t=>!t.future).length,0)],['Personnalités',clans.reduce((n,c)=>n+(c.characters||[]).length,0)]];
 stats.forEach(([label,value],i)=>{const card=el('article',`stat-card${i===0?' stat-card--total':''}`);card.append(el('span','stat-card__label',label),el('strong','stat-card__value',value));document.querySelector('#stats').append(card);});
 function matches(c) { const record=records.find(r=>r.id===c.id); const terms=[c.name,c.tagline,...c.specialties,...(c.techniques||[]).filter(t=>t.enabled&&!t.adminOnly&&['public','name-only'].includes(t.visibility)).map(t=>t.name),...(c.characters||[]).map(p=>p.name)].join(' ');const hit=normalize(terms).includes(normalize(state.query));const f=state.filter;return hit&&(f==='Tous'||f===village(c,config)||c.tags.includes(f)||(f==='Clan ouvert'&&isOpen(record))||(f==='Clan disparu'&&c.status==='disappeared')||(f==='Sans clan'&&c.id==='sans-clan')); }
 function render(){const found=clans.filter(matches);grid.replaceChildren();for(const c of found){const card=el('article','clan-card');card.dataset.status=c.status;const main=el('div','clan-card__main');const header=el('div','clan-card__header');const identity=el('div','clan-card__identity');const name=el('div');name.append(el('span','archive-number',`DOSSIER ${String(clans.indexOf(c)+1).padStart(2,'0')}`),el('h3','',c.displayName));identity.append(emblem(c),name);header.append(identity,el('span','status-badge',c.status==='active'?'Actif':'Disparu'));main.append(header,el('p','archive-tagline',c.tagline));const dl=el('dl','archive-facts');const r=records.find(r=>r.id===c.id);for(const [label,value] of [['Village actuel',village(c,config)],['Affinité principale',c.elements.join(' · ')||'Libre'],['Spécialité',c.specialties[0]],['Membres recensés',`${r.members.length} / ${r.maxMembers}`]]){const item=el('div');item.append(el('dt','',label),el('dd','',value));dl.append(item);}main.append(dl);const a=link('Consulter les archives',clanURL(c.id),'archive-link');a.setAttribute('aria-label',`Consulter les archives ${c.name}`);card.append(main,a);grid.append(card);}document.querySelector('#result-count').textContent=`${found.length} / ${clans.length} clans affichés`;document.querySelector('#empty-message').hidden=found.length>0;}
 for(const f of filters){const button=el('button','filter-button',f);button.type='button';button.dataset.filter=f;button.setAttribute('aria-pressed',String(f===state.filter));button.classList.toggle('is-active',f===state.filter);button.onclick=()=>{state.filter=f;document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('is-active',b===button);b.setAttribute('aria-pressed',String(b===button));});render();};document.querySelector('#filters').append(button);}
 document.querySelector('#search').oninput=e=>{state.query=e.target.value;render();};
 document.querySelector('#reset').onclick=()=>{state.query='';document.querySelector('#search').value='';document.querySelector('[data-filter="Tous"]').click();};render();
} catch(error){showError(error);} finally {grid.setAttribute('aria-busy','false');}

